### ISSUE TITLE
Bug: urllib.error.URLError: urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate

### ISSUE THREAD

**Issue by Martouta** [Martouta/speech_processor#21]
> marta@Martas-MacBook-Pro speech_processor % MAX_THREADS=8 INPUT_FILE='tests/fixtures/example_input.json' SPEECH_ENV='production' SUBS_LOCATION='file' python3 -u .
> 
> 2021-10-25 04:00:50,661 - root - INFO - [1/6] Downloading multimedia from URL ... [123145541492736-id_zWQJqt_D-vo-10-25.02:00:50661682]
> 2021-10-25 04:00:50,662 - root - INFO - [1/6] Downloading multimedia from URL ... [123145546747904-id_CNHe4qXqsck-10-25.02:00:50662092]
> 2021-10-25 04:00:50,725 - root - ERROR - <class 'urllib.error.URLError'> : <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)>
>     TRACEBACK:
>     Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1350, in do_open
>     encode_chunked=req.has_header('Transfer-encoding'))
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1277, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1323, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1272, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1032, in _send_output
>     self.send(msg)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 972, in send
>     self.connect()
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1447, in connect
>     server_hostname=server_hostname)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 423, in wrap_socket
>     session=session
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 870, in _create
>     self.do_handshake()
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1139, in do_handshake
>     self._sslobj.do_handshake()
> ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "./app/process_resource.py", line 14, in process_resource
>     return __process_resource(json_parsed)
>   File "./app/process_resource.py", line 29, in __process_resource
>     filepath = download_multimedia_from_url(recognition_id, json_parsed)
>   File "./app/download_multimedia_from_url.py", line 20, in download_multimedia_from_url
>     __download_youtube_video(json_parsed['youtube_reference_id'], fp_tuple)
>   File "./app/download_multimedia_from_url.py", line 34, in __download_youtube_video
>     YouTube(f"youtube.com/watch?v={youtube_reference_id}") \
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/__main__.py", line 291, in streams
>     self.check_availability()
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/__main__.py", line 206, in check_availability
>     status, messages = extract.playability_status(self.watch_html)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/__main__.py", line 98, in watch_html
>     self._watch_html = request.get(url=self.watch_url)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/request.py", line 53, in get
>     response = _execute_request(url, headers=extra_headers, timeout=timeout)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/request.py", line 37, in _execute_request
>     return urlopen(request, timeout=timeout)  # nosec
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
>     return opener.open(url, data, timeout)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
>     response = self._open(req, data)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
>     '_open', req)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
>     result = func(*args)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1393, in https_open
>     context=self._context, check_hostname=self._check_hostname)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1352, in do_open
>     raise URLError(err)
> urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)>
> 2021-10-25 04:00:50,725 - root - ERROR - <class 'urllib.error.URLError'> : <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)>
>     TRACEBACK:
>     Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1350, in do_open
>     encode_chunked=req.has_header('Transfer-encoding'))
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1277, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1323, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1272, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1032, in _send_output
>     self.send(msg)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 972, in send
>     self.connect()
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1447, in connect
>     server_hostname=server_hostname)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 423, in wrap_socket
>     session=session
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 870, in _create
>     self.do_handshake()
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1139, in do_handshake
>     self._sslobj.do_handshake()
> ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "./app/process_resource.py", line 14, in process_resource
>     return __process_resource(json_parsed)
>   File "./app/process_resource.py", line 29, in __process_resource
>     filepath = download_multimedia_from_url(recognition_id, json_parsed)
>   File "./app/download_multimedia_from_url.py", line 20, in download_multimedia_from_url
>     __download_youtube_video(json_parsed['youtube_reference_id'], fp_tuple)
>   File "./app/download_multimedia_from_url.py", line 34, in __download_youtube_video
>     YouTube(f"youtube.com/watch?v={youtube_reference_id}") \
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/__main__.py", line 291, in streams
>     self.check_availability()
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/__main__.py", line 206, in check_availability
>     status, messages = extract.playability_status(self.watch_html)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/__main__.py", line 98, in watch_html
>     self._watch_html = request.get(url=self.watch_url)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/request.py", line 53, in get
>     response = _execute_request(url, headers=extra_headers, timeout=timeout)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/request.py", line 37, in _execute_request
>     return urlopen(request, timeout=timeout)  # nosec
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
>     return opener.open(url, data, timeout)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
>     response = self._open(req, data)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
>     '_open', req)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
>     result = func(*args)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1393, in https_open
>     context=self._context, check_hostname=self._check_hostname)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1352, in do_open
>     raise URLError(err)
> urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)>
> 2021-10-25 04:00:50,727 - root - ERROR - <class 'urllib.error.URLError'> : <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)>
>     TRACEBACK:
>     Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1350, in do_open
>     encode_chunked=req.has_header('Transfer-encoding'))
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1277, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1323, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1272, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1032, in _send_output
>     self.send(msg)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 972, in send
>     self.connect()
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1447, in connect
>     server_hostname=server_hostname)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 423, in wrap_socket
>     session=session
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 870, in _create
>     self.do_handshake()
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1139, in do_handshake
>     self._sslobj.do_handshake()
> ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "./app/process_resource.py", line 14, in process_resource
>     return __process_resource(json_parsed)
>   File "./app/process_resource.py", line 29, in __process_resource
>     filepath = download_multimedia_from_url(recognition_id, json_parsed)
>   File "./app/download_multimedia_from_url.py", line 20, in download_multimedia_from_url
>     __download_youtube_video(json_parsed['youtube_reference_id'], fp_tuple)
>   File "./app/download_multimedia_from_url.py", line 34, in __download_youtube_video
>     YouTube(f"youtube.com/watch?v={youtube_reference_id}") \
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/__main__.py", line 291, in streams
>     self.check_availability()
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/__main__.py", line 206, in check_availability
>     status, messages = extract.playability_status(self.watch_html)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/__main__.py", line 98, in watch_html
>     self._watch_html = request.get(url=self.watch_url)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/request.py", line 53, in get
>     response = _execute_request(url, headers=extra_headers, timeout=timeout)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/request.py", line 37, in _execute_request
>     return urlopen(request, timeout=timeout)  # nosec
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
>     return opener.open(url, data, timeout)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
>     response = self._open(req, data)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
>     '_open', req)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
>     result = func(*args)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1393, in https_open
>     context=self._context, check_hostname=self._check_hostname)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1352, in do_open
>     raise URLError(err)
> urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)>
> 2021-10-25 04:00:50,727 - root - ERROR - <class 'urllib.error.URLError'> : <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)>
>     TRACEBACK:
>     Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1350, in do_open
>     encode_chunked=req.has_header('Transfer-encoding'))
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1277, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1323, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1272, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1032, in _send_output
>     self.send(msg)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 972, in send
>     self.connect()
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1447, in connect
>     server_hostname=server_hostname)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 423, in wrap_socket
>     session=session
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 870, in _create
>     self.do_handshake()
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1139, in do_handshake
>     self._sslobj.do_handshake()
> ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "./app/process_resource.py", line 14, in process_resource
>     return __process_resource(json_parsed)
>   File "./app/process_resource.py", line 29, in __process_resource
>     filepath = download_multimedia_from_url(recognition_id, json_parsed)
>   File "./app/download_multimedia_from_url.py", line 20, in download_multimedia_from_url
>     __download_youtube_video(json_parsed['youtube_reference_id'], fp_tuple)
>   File "./app/download_multimedia_from_url.py", line 34, in __download_youtube_video
>     YouTube(f"youtube.com/watch?v={youtube_reference_id}") \
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/__main__.py", line 291, in streams
>     self.check_availability()
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/__main__.py", line 206, in check_availability
>     status, messages = extract.playability_status(self.watch_html)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/__main__.py", line 98, in watch_html
>     self._watch_html = request.get(url=self.watch_url)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/request.py", line 53, in get
>     response = _execute_request(url, headers=extra_headers, timeout=timeout)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/request.py", line 37, in _execute_request
>     return urlopen(request, timeout=timeout)  # nosec
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
>     return opener.open(url, data, timeout)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
>     response = self._open(req, data)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
>     '_open', req)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
>     result = func(*args)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1393, in https_open
>     context=self._context, check_hostname=self._check_hostname)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1352, in do_open
>     raise URLError(err)
> urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)>
> 
>

**Comment by Martouta** [comment]
@Fenris-Wolff It means that, for protection, it is not allowing you to use the Python of the wide system. You could run the following instead, which means to run the Python of your local user (in `/usr/local/lib/python3.8` instead of `/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8`)  : 

1. Install packages: `pip3 install --no-cache-dir -r requirements.txt --user`
2. Run the program: `MAX_THREADS=8 INPUT_FILE='example_input.json' SPEECH_ENV='production' SUBS_LOCATION='file' python3 -u . --user`

See that the only difference is adding the `--user` at the end.
Let me know how that goes, please 👍🏼 Because if that works, I will update the documentation accordingly 😄 

Btw, once you solve that problem, you will encounter the error `'NoneType' object has no attribute 'span'`, but that will be fixed in https://github.com/pytube/pytube/pull/1230 (hopefully by the end of the week, according to the comments there).

**Comment by Fenris-Wolff** [comment]
First of all thanks for the answer! However, unfortunately it did not work for me. When typing the first command in the Terminal this Message appeared: 

“ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'“

When typing in the second command, this error message appeared (although I guess the first one should've worked in order for the second one to work?):

" /Library/Frameworks/Python.framework/Versions/3.8/bin/python3: can't find '__main__' module in '.' "

Also, adding "--user" to the  "open /Applications/Python\ 3.8/Install\ Certificates.command" command didn't work, as it apparently doesn't make sense to add "--user" to it ("unrecognized option `--user' ")

**Comment by Martouta** [comment]
@Fenris-Wolff As a general rule, do not run the next command if the previous one did not work 😄 In this case, running the program cannot work if the dependencies have not been installed.

That error of "requirements.txt" not found is because you do not have that file in the path where you are located when you try to install the dependencies. In order to work, you have to do run those commands inside the path where you have downloaded the program (download the latest release so far https://github.com/Martouta/speech_processor/releases/tag/v1.0.5 and uncompress it).

So you could do, for example:

1. Move to wherever you want to download it, for example: `cd ~/Downloads`
2. Download the current latest version (v1.0.5): `curl -OL https://github.com/Martouta/speech_processor/archive/refs/tags/v1.0.5.tar.gz`
3. Uncompress the downloaded file: `tar -xzvf v1.0.5.tar.gz`
4. Move to the uncompressed folder of the program: `cd speech_processor-1.0.5`
5. Install packages: `pip3 install --no-cache-dir -r requirements.txt --user`
6. Run the program: `MAX_THREADS=8 INPUT_FILE='example_input.json' SPEECH_ENV='production' SUBS_LOCATION='file' python3 -u . --user`

For running the program, as I mentioned in [the documentation](https://github.com/Martouta/speech_processor/blob/ba2c3e2a8cabb8a181d5e8566fa937bcf83109a5/README.md#run-the-program), I am assuming that 'example_input.json' is a file that you created yourself in that same folder (or in another folder if you send the whole path), with the format and data mentioned in the documentation.
